package com.company.Tests;

import io.restassured.http.Header;
import io.restassured.http.Headers;
import io.restassured.path.json.JsonPath;

import static io.restassured.RestAssured.*;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Assert;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.Test;

import static org.hamcrest.Matchers.*;

import java.net.ResponseCache;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GET_Cyber_Practice {

    @Test
    public void testingTask() {
        baseURI = "https://api.github.com";
        Response res =
                given().log().all()
                        .pathParam("username", "ali")
                        .queryParam("type", "member")
                        .queryParam("sort", "pushed")
                        .queryParam("direction", "desc")
                        .accept(ContentType.JSON)
                        .when()
                        .log().ifValidationFails()  // will print where it fails
                        .log().headers()
                        .log().cookies()
                        .get("/users/{username}/repos")
                        .then().assertThat()
                        .statusCode(200)
                        .contentType(ContentType.JSON)
                        .body("name[4]", equalTo("hatch"))
                        .body("owner[4].id", equalTo(2610172))
                        .extract().response();
        res.prettyPrint();
        // Verify there is 11 id's in response
        JsonPath js = res.jsonPath();
        //Asserting response body element with jsonPath
        Assert.assertEquals(js.getString("name[4]"), "hatch");
        Assert.assertEquals(js.getInt("owner[4].id"), 2610172);
        // Size of response array
        int idSize = js.getInt("id.size()");
        int nameSize = js.getInt("name.size()");
        Assert.assertEquals(idSize, 11);
        Assert.assertEquals(nameSize, 11);

        // Get all names in response -because here there is not main array's name in response
        List<String> namesList = js.getList("name");
        List<Integer> idList = js.getList("id");
        System.out.println(namesList);
        System.out.println(idList);

        // Verify 5th name is hatch
        String name_5th = namesList.get(4);
        Assert.assertEquals(name_5th, "hatch");
        //direct
        Assert.assertEquals(js.getString("name[4]"), "hatch");

        // Verify owner id of 5th person is 2610172
        List<Integer> allOwnerIds = js.getList("owner.id");
        int id_5th = allOwnerIds.get(4);
        Assert.assertEquals(id_5th, 2610172);

        // Find all cookies in response
        Map<String, String> cookies = res.getCookies();
        System.out.println("Printing all cookies in response");
        for (String cookieName : cookies.keySet()) {
            System.out.println(cookieName + " " + cookies.get(cookieName));
        }
        //Find all Headers in response
        Headers headers = res.getHeaders();
        Map<String, String> headersMap = new HashMap<>();
        for (Header header : headers) {
            headersMap.put(header.getName(), header.getValue());
        }
        System.out.println(headersMap.toString());
    }
    //Open response here
    /**
     * [
     *     {
     *         "id": 106751928,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkxMDY3NTE5Mjg=",
     *         "name": "canvas",
     *         "full_name": "HubSpot/canvas",
     *         "private": false,
     *         "owner": {
     *             "login": "HubSpot",
     *             "id": 326419,
     *             "node_id": "MDEyOk9yZ2FuaXphdGlvbjMyNjQxOQ==",
     *             "avatar_url": "https://avatars2.githubusercontent.com/u/326419?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/HubSpot",
     *             "html_url": "https://github.com/HubSpot",
     *             "followers_url": "https://api.github.com/users/HubSpot/followers",
     *             "following_url": "https://api.github.com/users/HubSpot/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/HubSpot/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/HubSpot/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/HubSpot/subscriptions",
     *             "organizations_url": "https://api.github.com/users/HubSpot/orgs",
     *             "repos_url": "https://api.github.com/users/HubSpot/repos",
     *             "events_url": "https://api.github.com/users/HubSpot/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/HubSpot/received_events",
     *             "type": "Organization",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/HubSpot/canvas",
     *         "description": "HubSpot Canvas is the design system that we at HubSpot use to build our products.",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/HubSpot/canvas",
     *         "forks_url": "https://api.github.com/repos/HubSpot/canvas/forks",
     *         "keys_url": "https://api.github.com/repos/HubSpot/canvas/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/HubSpot/canvas/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/HubSpot/canvas/teams",
     *         "hooks_url": "https://api.github.com/repos/HubSpot/canvas/hooks",
     *         "issue_events_url": "https://api.github.com/repos/HubSpot/canvas/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/HubSpot/canvas/events",
     *         "assignees_url": "https://api.github.com/repos/HubSpot/canvas/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/HubSpot/canvas/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/HubSpot/canvas/tags",
     *         "blobs_url": "https://api.github.com/repos/HubSpot/canvas/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/HubSpot/canvas/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/HubSpot/canvas/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/HubSpot/canvas/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/HubSpot/canvas/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/HubSpot/canvas/languages",
     *         "stargazers_url": "https://api.github.com/repos/HubSpot/canvas/stargazers",
     *         "contributors_url": "https://api.github.com/repos/HubSpot/canvas/contributors",
     *         "subscribers_url": "https://api.github.com/repos/HubSpot/canvas/subscribers",
     *         "subscription_url": "https://api.github.com/repos/HubSpot/canvas/subscription",
     *         "commits_url": "https://api.github.com/repos/HubSpot/canvas/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/HubSpot/canvas/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/HubSpot/canvas/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/HubSpot/canvas/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/HubSpot/canvas/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/HubSpot/canvas/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/HubSpot/canvas/merges",
     *         "archive_url": "https://api.github.com/repos/HubSpot/canvas/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/HubSpot/canvas/downloads",
     *         "issues_url": "https://api.github.com/repos/HubSpot/canvas/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/HubSpot/canvas/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/HubSpot/canvas/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/HubSpot/canvas/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/HubSpot/canvas/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/HubSpot/canvas/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/HubSpot/canvas/deployments",
     *         "created_at": "2017-10-12T22:30:59Z",
     *         "updated_at": "2020-06-24T04:08:03Z",
     *         "pushed_at": "2018-03-01T00:29:33Z",
     *         "git_url": "git://github.com/HubSpot/canvas.git",
     *         "ssh_url": "git@github.com:HubSpot/canvas.git",
     *         "clone_url": "https://github.com/HubSpot/canvas.git",
     *         "svn_url": "https://github.com/HubSpot/canvas",
     *         "homepage": "https://canvas.hubspot.com",
     *         "size": 102,
     *         "stargazers_count": 25,
     *         "watchers_count": 25,
     *         "language": "JavaScript",
     *         "has_issues": true,
     *         "has_projects": false,
     *         "has_downloads": true,
     *         "has_wiki": false,
     *         "has_pages": false,
     *         "forks_count": 6,
     *         "mirror_url": null,
     *         "archived": true,
     *         "disabled": false,
     *         "open_issues_count": 0,
     *         "license": null,
     *         "forks": 6,
     *         "open_issues": 0,
     *         "watchers": 25,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 34033716,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkzNDAzMzcxNg==",
     *         "name": "rusty_bars",
     *         "full_name": "PaulFurtado/rusty_bars",
     *         "private": false,
     *         "owner": {
     *             "login": "PaulFurtado",
     *             "id": 704936,
     *             "node_id": "MDQ6VXNlcjcwNDkzNg==",
     *             "avatar_url": "https://avatars1.githubusercontent.com/u/704936?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/PaulFurtado",
     *             "html_url": "https://github.com/PaulFurtado",
     *             "followers_url": "https://api.github.com/users/PaulFurtado/followers",
     *             "following_url": "https://api.github.com/users/PaulFurtado/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/PaulFurtado/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/PaulFurtado/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/PaulFurtado/subscriptions",
     *             "organizations_url": "https://api.github.com/users/PaulFurtado/orgs",
     *             "repos_url": "https://api.github.com/users/PaulFurtado/repos",
     *             "events_url": "https://api.github.com/users/PaulFurtado/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/PaulFurtado/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/PaulFurtado/rusty_bars",
     *         "description": "A PulseAudio visualizer written in Rust.",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/PaulFurtado/rusty_bars",
     *         "forks_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/forks",
     *         "keys_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/teams",
     *         "hooks_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/hooks",
     *         "issue_events_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/events",
     *         "assignees_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/tags",
     *         "blobs_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/languages",
     *         "stargazers_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/stargazers",
     *         "contributors_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/contributors",
     *         "subscribers_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/subscribers",
     *         "subscription_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/subscription",
     *         "commits_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/merges",
     *         "archive_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/downloads",
     *         "issues_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/PaulFurtado/rusty_bars/deployments",
     *         "created_at": "2015-04-16T04:09:33Z",
     *         "updated_at": "2020-06-01T17:45:42Z",
     *         "pushed_at": "2016-08-17T02:09:56Z",
     *         "git_url": "git://github.com/PaulFurtado/rusty_bars.git",
     *         "ssh_url": "git@github.com:PaulFurtado/rusty_bars.git",
     *         "clone_url": "https://github.com/PaulFurtado/rusty_bars.git",
     *         "svn_url": "https://github.com/PaulFurtado/rusty_bars",
     *         "homepage": null,
     *         "size": 2511,
     *         "stargazers_count": 34,
     *         "watchers_count": 34,
     *         "language": "Rust",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 3,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 1,
     *         "license": null,
     *         "forks": 3,
     *         "open_issues": 1,
     *         "watchers": 34,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 37663082,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkzNzY2MzA4Mg==",
     *         "name": "lights",
     *         "full_name": "wolfd/lights",
     *         "private": false,
     *         "owner": {
     *             "login": "wolfd",
     *             "id": 930169,
     *             "node_id": "MDQ6VXNlcjkzMDE2OQ==",
     *             "avatar_url": "https://avatars0.githubusercontent.com/u/930169?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/wolfd",
     *             "html_url": "https://github.com/wolfd",
     *             "followers_url": "https://api.github.com/users/wolfd/followers",
     *             "following_url": "https://api.github.com/users/wolfd/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/wolfd/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/wolfd/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/wolfd/subscriptions",
     *             "organizations_url": "https://api.github.com/users/wolfd/orgs",
     *             "repos_url": "https://api.github.com/users/wolfd/repos",
     *             "events_url": "https://api.github.com/users/wolfd/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/wolfd/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/wolfd/lights",
     *         "description": null,
     *         "fork": false,
     *         "url": "https://api.github.com/repos/wolfd/lights",
     *         "forks_url": "https://api.github.com/repos/wolfd/lights/forks",
     *         "keys_url": "https://api.github.com/repos/wolfd/lights/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/wolfd/lights/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/wolfd/lights/teams",
     *         "hooks_url": "https://api.github.com/repos/wolfd/lights/hooks",
     *         "issue_events_url": "https://api.github.com/repos/wolfd/lights/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/wolfd/lights/events",
     *         "assignees_url": "https://api.github.com/repos/wolfd/lights/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/wolfd/lights/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/wolfd/lights/tags",
     *         "blobs_url": "https://api.github.com/repos/wolfd/lights/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/wolfd/lights/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/wolfd/lights/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/wolfd/lights/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/wolfd/lights/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/wolfd/lights/languages",
     *         "stargazers_url": "https://api.github.com/repos/wolfd/lights/stargazers",
     *         "contributors_url": "https://api.github.com/repos/wolfd/lights/contributors",
     *         "subscribers_url": "https://api.github.com/repos/wolfd/lights/subscribers",
     *         "subscription_url": "https://api.github.com/repos/wolfd/lights/subscription",
     *         "commits_url": "https://api.github.com/repos/wolfd/lights/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/wolfd/lights/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/wolfd/lights/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/wolfd/lights/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/wolfd/lights/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/wolfd/lights/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/wolfd/lights/merges",
     *         "archive_url": "https://api.github.com/repos/wolfd/lights/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/wolfd/lights/downloads",
     *         "issues_url": "https://api.github.com/repos/wolfd/lights/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/wolfd/lights/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/wolfd/lights/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/wolfd/lights/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/wolfd/lights/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/wolfd/lights/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/wolfd/lights/deployments",
     *         "created_at": "2015-06-18T14:07:07Z",
     *         "updated_at": "2017-02-06T02:06:05Z",
     *         "pushed_at": "2015-07-03T17:12:11Z",
     *         "git_url": "git://github.com/wolfd/lights.git",
     *         "ssh_url": "git@github.com:wolfd/lights.git",
     *         "clone_url": "https://github.com/wolfd/lights.git",
     *         "svn_url": "https://github.com/wolfd/lights",
     *         "homepage": null,
     *         "size": 192,
     *         "stargazers_count": 0,
     *         "watchers_count": 0,
     *         "language": "Python",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 0,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 0,
     *         "watchers": 0,
     *         "default_branch": "hue"
     *     },
     *     {
     *         "id": 30030068,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkzMDAzMDA2OA==",
     *         "name": "hatch-back-end",
     *         "full_name": "pietdaniel/hatch-back-end",
     *         "private": false,
     *         "owner": {
     *             "login": "pietdaniel",
     *             "id": 1924983,
     *             "node_id": "MDQ6VXNlcjE5MjQ5ODM=",
     *             "avatar_url": "https://avatars3.githubusercontent.com/u/1924983?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/pietdaniel",
     *             "html_url": "https://github.com/pietdaniel",
     *             "followers_url": "https://api.github.com/users/pietdaniel/followers",
     *             "following_url": "https://api.github.com/users/pietdaniel/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/pietdaniel/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/pietdaniel/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/pietdaniel/subscriptions",
     *             "organizations_url": "https://api.github.com/users/pietdaniel/orgs",
     *             "repos_url": "https://api.github.com/users/pietdaniel/repos",
     *             "events_url": "https://api.github.com/users/pietdaniel/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/pietdaniel/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/pietdaniel/hatch-back-end",
     *         "description": "A Social Media Analysis Tool for CAMD and beyond!",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/pietdaniel/hatch-back-end",
     *         "forks_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/forks",
     *         "keys_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/teams",
     *         "hooks_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/hooks",
     *         "issue_events_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/events",
     *         "assignees_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/tags",
     *         "blobs_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/languages",
     *         "stargazers_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/stargazers",
     *         "contributors_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/contributors",
     *         "subscribers_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/subscribers",
     *         "subscription_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/subscription",
     *         "commits_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/merges",
     *         "archive_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/downloads",
     *         "issues_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/pietdaniel/hatch-back-end/deployments",
     *         "created_at": "2015-01-29T16:40:40Z",
     *         "updated_at": "2015-04-30T01:10:05Z",
     *         "pushed_at": "2015-04-30T01:10:04Z",
     *         "git_url": "git://github.com/pietdaniel/hatch-back-end.git",
     *         "ssh_url": "git@github.com:pietdaniel/hatch-back-end.git",
     *         "clone_url": "https://github.com/pietdaniel/hatch-back-end.git",
     *         "svn_url": "https://github.com/pietdaniel/hatch-back-end",
     *         "homepage": null,
     *         "size": 1018,
     *         "stargazers_count": 2,
     *         "watchers_count": 2,
     *         "language": "Python",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 3,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 2,
     *         "license": null,
     *         "forks": 3,
     *         "open_issues": 2,
     *         "watchers": 2,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 31230260,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkzMTIzMDI2MA==",
     *         "name": "hatch",
     *         "full_name": "dj/hatch",
     *         "private": false,
     *         "owner": {
     *             "login": "dj",
     *             "id": 2610172,
     *             "node_id": "MDQ6VXNlcjI2MTAxNzI=",
     *             "avatar_url": "https://avatars2.githubusercontent.com/u/2610172?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/dj",
     *             "html_url": "https://github.com/dj",
     *             "followers_url": "https://api.github.com/users/dj/followers",
     *             "following_url": "https://api.github.com/users/dj/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/dj/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/dj/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/dj/subscriptions",
     *             "organizations_url": "https://api.github.com/users/dj/orgs",
     *             "repos_url": "https://api.github.com/users/dj/repos",
     *             "events_url": "https://api.github.com/users/dj/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/dj/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/dj/hatch",
     *         "description": "CS4500: Twitter -> CSV for social scientists",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/dj/hatch",
     *         "forks_url": "https://api.github.com/repos/dj/hatch/forks",
     *         "keys_url": "https://api.github.com/repos/dj/hatch/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/dj/hatch/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/dj/hatch/teams",
     *         "hooks_url": "https://api.github.com/repos/dj/hatch/hooks",
     *         "issue_events_url": "https://api.github.com/repos/dj/hatch/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/dj/hatch/events",
     *         "assignees_url": "https://api.github.com/repos/dj/hatch/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/dj/hatch/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/dj/hatch/tags",
     *         "blobs_url": "https://api.github.com/repos/dj/hatch/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/dj/hatch/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/dj/hatch/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/dj/hatch/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/dj/hatch/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/dj/hatch/languages",
     *         "stargazers_url": "https://api.github.com/repos/dj/hatch/stargazers",
     *         "contributors_url": "https://api.github.com/repos/dj/hatch/contributors",
     *         "subscribers_url": "https://api.github.com/repos/dj/hatch/subscribers",
     *         "subscription_url": "https://api.github.com/repos/dj/hatch/subscription",
     *         "commits_url": "https://api.github.com/repos/dj/hatch/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/dj/hatch/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/dj/hatch/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/dj/hatch/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/dj/hatch/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/dj/hatch/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/dj/hatch/merges",
     *         "archive_url": "https://api.github.com/repos/dj/hatch/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/dj/hatch/downloads",
     *         "issues_url": "https://api.github.com/repos/dj/hatch/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/dj/hatch/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/dj/hatch/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/dj/hatch/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/dj/hatch/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/dj/hatch/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/dj/hatch/deployments",
     *         "created_at": "2015-02-23T21:17:14Z",
     *         "updated_at": "2015-04-30T00:53:34Z",
     *         "pushed_at": "2015-04-30T00:53:34Z",
     *         "git_url": "git://github.com/dj/hatch.git",
     *         "ssh_url": "git@github.com:dj/hatch.git",
     *         "clone_url": "https://github.com/dj/hatch.git",
     *         "svn_url": "https://github.com/dj/hatch",
     *         "homepage": null,
     *         "size": 944,
     *         "stargazers_count": 0,
     *         "watchers_count": 0,
     *         "language": "CSS",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 0,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 0,
     *         "watchers": 0,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 3023421,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkzMDIzNDIx",
     *         "name": "BPASafe",
     *         "full_name": "alisha/BPASafe",
     *         "private": false,
     *         "owner": {
     *             "login": "alisha",
     *             "id": 1406727,
     *             "node_id": "MDQ6VXNlcjE0MDY3Mjc=",
     *             "avatar_url": "https://avatars3.githubusercontent.com/u/1406727?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/alisha",
     *             "html_url": "https://github.com/alisha",
     *             "followers_url": "https://api.github.com/users/alisha/followers",
     *             "following_url": "https://api.github.com/users/alisha/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/alisha/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/alisha/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/alisha/subscriptions",
     *             "organizations_url": "https://api.github.com/users/alisha/orgs",
     *             "repos_url": "https://api.github.com/users/alisha/repos",
     *             "events_url": "https://api.github.com/users/alisha/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/alisha/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/alisha/BPASafe",
     *         "description": null,
     *         "fork": false,
     *         "url": "https://api.github.com/repos/alisha/BPASafe",
     *         "forks_url": "https://api.github.com/repos/alisha/BPASafe/forks",
     *         "keys_url": "https://api.github.com/repos/alisha/BPASafe/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/alisha/BPASafe/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/alisha/BPASafe/teams",
     *         "hooks_url": "https://api.github.com/repos/alisha/BPASafe/hooks",
     *         "issue_events_url": "https://api.github.com/repos/alisha/BPASafe/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/alisha/BPASafe/events",
     *         "assignees_url": "https://api.github.com/repos/alisha/BPASafe/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/alisha/BPASafe/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/alisha/BPASafe/tags",
     *         "blobs_url": "https://api.github.com/repos/alisha/BPASafe/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/alisha/BPASafe/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/alisha/BPASafe/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/alisha/BPASafe/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/alisha/BPASafe/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/alisha/BPASafe/languages",
     *         "stargazers_url": "https://api.github.com/repos/alisha/BPASafe/stargazers",
     *         "contributors_url": "https://api.github.com/repos/alisha/BPASafe/contributors",
     *         "subscribers_url": "https://api.github.com/repos/alisha/BPASafe/subscribers",
     *         "subscription_url": "https://api.github.com/repos/alisha/BPASafe/subscription",
     *         "commits_url": "https://api.github.com/repos/alisha/BPASafe/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/alisha/BPASafe/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/alisha/BPASafe/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/alisha/BPASafe/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/alisha/BPASafe/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/alisha/BPASafe/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/alisha/BPASafe/merges",
     *         "archive_url": "https://api.github.com/repos/alisha/BPASafe/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/alisha/BPASafe/downloads",
     *         "issues_url": "https://api.github.com/repos/alisha/BPASafe/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/alisha/BPASafe/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/alisha/BPASafe/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/alisha/BPASafe/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/alisha/BPASafe/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/alisha/BPASafe/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/alisha/BPASafe/deployments",
     *         "created_at": "2011-12-20T23:36:30Z",
     *         "updated_at": "2014-11-14T10:14:03Z",
     *         "pushed_at": "2014-05-25T01:32:04Z",
     *         "git_url": "git://github.com/alisha/BPASafe.git",
     *         "ssh_url": "git@github.com:alisha/BPASafe.git",
     *         "clone_url": "https://github.com/alisha/BPASafe.git",
     *         "svn_url": "https://github.com/alisha/BPASafe",
     *         "homepage": "http://bpasafe.net",
     *         "size": 170,
     *         "stargazers_count": 1,
     *         "watchers_count": 1,
     *         "language": "CSS",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": true,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 0,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 0,
     *         "watchers": 1,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 14462716,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkxNDQ2MjcxNg==",
     *         "name": "lambda3",
     *         "full_name": "joshcaron/lambda3",
     *         "private": false,
     *         "owner": {
     *             "login": "joshcaron",
     *             "id": 2482285,
     *             "node_id": "MDQ6VXNlcjI0ODIyODU=",
     *             "avatar_url": "https://avatars1.githubusercontent.com/u/2482285?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/joshcaron",
     *             "html_url": "https://github.com/joshcaron",
     *             "followers_url": "https://api.github.com/users/joshcaron/followers",
     *             "following_url": "https://api.github.com/users/joshcaron/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/joshcaron/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/joshcaron/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/joshcaron/subscriptions",
     *             "organizations_url": "https://api.github.com/users/joshcaron/orgs",
     *             "repos_url": "https://api.github.com/users/joshcaron/repos",
     *             "events_url": "https://api.github.com/users/joshcaron/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/joshcaron/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/joshcaron/lambda3",
     *         "description": "The open-source fraternity",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/joshcaron/lambda3",
     *         "forks_url": "https://api.github.com/repos/joshcaron/lambda3/forks",
     *         "keys_url": "https://api.github.com/repos/joshcaron/lambda3/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/joshcaron/lambda3/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/joshcaron/lambda3/teams",
     *         "hooks_url": "https://api.github.com/repos/joshcaron/lambda3/hooks",
     *         "issue_events_url": "https://api.github.com/repos/joshcaron/lambda3/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/joshcaron/lambda3/events",
     *         "assignees_url": "https://api.github.com/repos/joshcaron/lambda3/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/joshcaron/lambda3/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/joshcaron/lambda3/tags",
     *         "blobs_url": "https://api.github.com/repos/joshcaron/lambda3/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/joshcaron/lambda3/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/joshcaron/lambda3/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/joshcaron/lambda3/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/joshcaron/lambda3/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/joshcaron/lambda3/languages",
     *         "stargazers_url": "https://api.github.com/repos/joshcaron/lambda3/stargazers",
     *         "contributors_url": "https://api.github.com/repos/joshcaron/lambda3/contributors",
     *         "subscribers_url": "https://api.github.com/repos/joshcaron/lambda3/subscribers",
     *         "subscription_url": "https://api.github.com/repos/joshcaron/lambda3/subscription",
     *         "commits_url": "https://api.github.com/repos/joshcaron/lambda3/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/joshcaron/lambda3/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/joshcaron/lambda3/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/joshcaron/lambda3/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/joshcaron/lambda3/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/joshcaron/lambda3/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/joshcaron/lambda3/merges",
     *         "archive_url": "https://api.github.com/repos/joshcaron/lambda3/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/joshcaron/lambda3/downloads",
     *         "issues_url": "https://api.github.com/repos/joshcaron/lambda3/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/joshcaron/lambda3/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/joshcaron/lambda3/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/joshcaron/lambda3/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/joshcaron/lambda3/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/joshcaron/lambda3/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/joshcaron/lambda3/deployments",
     *         "created_at": "2013-11-17T07:03:59Z",
     *         "updated_at": "2015-03-11T20:47:13Z",
     *         "pushed_at": "2013-11-17T07:07:04Z",
     *         "git_url": "git://github.com/joshcaron/lambda3.git",
     *         "ssh_url": "git@github.com:joshcaron/lambda3.git",
     *         "clone_url": "https://github.com/joshcaron/lambda3.git",
     *         "svn_url": "https://github.com/joshcaron/lambda3",
     *         "homepage": null,
     *         "size": 236,
     *         "stargazers_count": 0,
     *         "watchers_count": 0,
     *         "language": "CSS",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 0,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 0,
     *         "watchers": 0,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 3498621,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkzNDk4NjIx",
     *         "name": "cardslap",
     *         "full_name": "ehmorris/cardslap",
     *         "private": false,
     *         "owner": {
     *             "login": "ehmorris",
     *             "id": 654275,
     *             "node_id": "MDQ6VXNlcjY1NDI3NQ==",
     *             "avatar_url": "https://avatars0.githubusercontent.com/u/654275?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/ehmorris",
     *             "html_url": "https://github.com/ehmorris",
     *             "followers_url": "https://api.github.com/users/ehmorris/followers",
     *             "following_url": "https://api.github.com/users/ehmorris/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/ehmorris/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/ehmorris/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/ehmorris/subscriptions",
     *             "organizations_url": "https://api.github.com/users/ehmorris/orgs",
     *             "repos_url": "https://api.github.com/users/ehmorris/repos",
     *             "events_url": "https://api.github.com/users/ehmorris/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/ehmorris/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/ehmorris/cardslap",
     *         "description": "A flashcard app. Made to help me learn rails.",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/ehmorris/cardslap",
     *         "forks_url": "https://api.github.com/repos/ehmorris/cardslap/forks",
     *         "keys_url": "https://api.github.com/repos/ehmorris/cardslap/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/ehmorris/cardslap/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/ehmorris/cardslap/teams",
     *         "hooks_url": "https://api.github.com/repos/ehmorris/cardslap/hooks",
     *         "issue_events_url": "https://api.github.com/repos/ehmorris/cardslap/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/ehmorris/cardslap/events",
     *         "assignees_url": "https://api.github.com/repos/ehmorris/cardslap/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/ehmorris/cardslap/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/ehmorris/cardslap/tags",
     *         "blobs_url": "https://api.github.com/repos/ehmorris/cardslap/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/ehmorris/cardslap/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/ehmorris/cardslap/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/ehmorris/cardslap/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/ehmorris/cardslap/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/ehmorris/cardslap/languages",
     *         "stargazers_url": "https://api.github.com/repos/ehmorris/cardslap/stargazers",
     *         "contributors_url": "https://api.github.com/repos/ehmorris/cardslap/contributors",
     *         "subscribers_url": "https://api.github.com/repos/ehmorris/cardslap/subscribers",
     *         "subscription_url": "https://api.github.com/repos/ehmorris/cardslap/subscription",
     *         "commits_url": "https://api.github.com/repos/ehmorris/cardslap/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/ehmorris/cardslap/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/ehmorris/cardslap/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/ehmorris/cardslap/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/ehmorris/cardslap/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/ehmorris/cardslap/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/ehmorris/cardslap/merges",
     *         "archive_url": "https://api.github.com/repos/ehmorris/cardslap/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/ehmorris/cardslap/downloads",
     *         "issues_url": "https://api.github.com/repos/ehmorris/cardslap/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/ehmorris/cardslap/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/ehmorris/cardslap/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/ehmorris/cardslap/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/ehmorris/cardslap/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/ehmorris/cardslap/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/ehmorris/cardslap/deployments",
     *         "created_at": "2012-02-20T22:38:20Z",
     *         "updated_at": "2019-04-01T18:40:31Z",
     *         "pushed_at": "2013-05-20T05:51:59Z",
     *         "git_url": "git://github.com/ehmorris/cardslap.git",
     *         "ssh_url": "git@github.com:ehmorris/cardslap.git",
     *         "clone_url": "https://github.com/ehmorris/cardslap.git",
     *         "svn_url": "https://github.com/ehmorris/cardslap",
     *         "homepage": "http://cardslap.herokuapp.com/",
     *         "size": 1460,
     *         "stargazers_count": 0,
     *         "watchers_count": 0,
     *         "language": "Ruby",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": false,
     *         "has_pages": false,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 13,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 13,
     *         "watchers": 0,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 3612783,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkzNjEyNzgz",
     *         "name": "hackrtools",
     *         "full_name": "wylieconlon/hackrtools",
     *         "private": false,
     *         "owner": {
     *             "login": "wylieconlon",
     *             "id": 666475,
     *             "node_id": "MDQ6VXNlcjY2NjQ3NQ==",
     *             "avatar_url": "https://avatars2.githubusercontent.com/u/666475?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/wylieconlon",
     *             "html_url": "https://github.com/wylieconlon",
     *             "followers_url": "https://api.github.com/users/wylieconlon/followers",
     *             "following_url": "https://api.github.com/users/wylieconlon/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/wylieconlon/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/wylieconlon/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/wylieconlon/subscriptions",
     *             "organizations_url": "https://api.github.com/users/wylieconlon/orgs",
     *             "repos_url": "https://api.github.com/users/wylieconlon/repos",
     *             "events_url": "https://api.github.com/users/wylieconlon/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/wylieconlon/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/wylieconlon/hackrtools",
     *         "description": "Simple Rails app. Save code snippets or articles for future use.",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/wylieconlon/hackrtools",
     *         "forks_url": "https://api.github.com/repos/wylieconlon/hackrtools/forks",
     *         "keys_url": "https://api.github.com/repos/wylieconlon/hackrtools/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/wylieconlon/hackrtools/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/wylieconlon/hackrtools/teams",
     *         "hooks_url": "https://api.github.com/repos/wylieconlon/hackrtools/hooks",
     *         "issue_events_url": "https://api.github.com/repos/wylieconlon/hackrtools/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/wylieconlon/hackrtools/events",
     *         "assignees_url": "https://api.github.com/repos/wylieconlon/hackrtools/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/wylieconlon/hackrtools/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/wylieconlon/hackrtools/tags",
     *         "blobs_url": "https://api.github.com/repos/wylieconlon/hackrtools/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/wylieconlon/hackrtools/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/wylieconlon/hackrtools/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/wylieconlon/hackrtools/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/wylieconlon/hackrtools/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/wylieconlon/hackrtools/languages",
     *         "stargazers_url": "https://api.github.com/repos/wylieconlon/hackrtools/stargazers",
     *         "contributors_url": "https://api.github.com/repos/wylieconlon/hackrtools/contributors",
     *         "subscribers_url": "https://api.github.com/repos/wylieconlon/hackrtools/subscribers",
     *         "subscription_url": "https://api.github.com/repos/wylieconlon/hackrtools/subscription",
     *         "commits_url": "https://api.github.com/repos/wylieconlon/hackrtools/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/wylieconlon/hackrtools/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/wylieconlon/hackrtools/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/wylieconlon/hackrtools/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/wylieconlon/hackrtools/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/wylieconlon/hackrtools/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/wylieconlon/hackrtools/merges",
     *         "archive_url": "https://api.github.com/repos/wylieconlon/hackrtools/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/wylieconlon/hackrtools/downloads",
     *         "issues_url": "https://api.github.com/repos/wylieconlon/hackrtools/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/wylieconlon/hackrtools/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/wylieconlon/hackrtools/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/wylieconlon/hackrtools/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/wylieconlon/hackrtools/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/wylieconlon/hackrtools/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/wylieconlon/hackrtools/deployments",
     *         "created_at": "2012-03-03T18:43:30Z",
     *         "updated_at": "2014-01-28T21:00:43Z",
     *         "pushed_at": "2013-04-23T21:29:36Z",
     *         "git_url": "git://github.com/wylieconlon/hackrtools.git",
     *         "ssh_url": "git@github.com:wylieconlon/hackrtools.git",
     *         "clone_url": "https://github.com/wylieconlon/hackrtools.git",
     *         "svn_url": "https://github.com/wylieconlon/hackrtools",
     *         "homepage": "http://hackrtools.herokuapp.com/",
     *         "size": 370,
     *         "stargazers_count": 1,
     *         "watchers_count": 1,
     *         "language": "Ruby",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 0,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 0,
     *         "watchers": 1,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 2739504,
     *         "node_id": "MDEwOlJlcG9zaXRvcnkyNzM5NTA0",
     *         "name": "courses",
     *         "full_name": "ehmorris/courses",
     *         "private": false,
     *         "owner": {
     *             "login": "ehmorris",
     *             "id": 654275,
     *             "node_id": "MDQ6VXNlcjY1NDI3NQ==",
     *             "avatar_url": "https://avatars0.githubusercontent.com/u/654275?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/ehmorris",
     *             "html_url": "https://github.com/ehmorris",
     *             "followers_url": "https://api.github.com/users/ehmorris/followers",
     *             "following_url": "https://api.github.com/users/ehmorris/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/ehmorris/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/ehmorris/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/ehmorris/subscriptions",
     *             "organizations_url": "https://api.github.com/users/ehmorris/orgs",
     *             "repos_url": "https://api.github.com/users/ehmorris/repos",
     *             "events_url": "https://api.github.com/users/ehmorris/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/ehmorris/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/ehmorris/courses",
     *         "description": null,
     *         "fork": false,
     *         "url": "https://api.github.com/repos/ehmorris/courses",
     *         "forks_url": "https://api.github.com/repos/ehmorris/courses/forks",
     *         "keys_url": "https://api.github.com/repos/ehmorris/courses/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/ehmorris/courses/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/ehmorris/courses/teams",
     *         "hooks_url": "https://api.github.com/repos/ehmorris/courses/hooks",
     *         "issue_events_url": "https://api.github.com/repos/ehmorris/courses/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/ehmorris/courses/events",
     *         "assignees_url": "https://api.github.com/repos/ehmorris/courses/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/ehmorris/courses/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/ehmorris/courses/tags",
     *         "blobs_url": "https://api.github.com/repos/ehmorris/courses/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/ehmorris/courses/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/ehmorris/courses/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/ehmorris/courses/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/ehmorris/courses/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/ehmorris/courses/languages",
     *         "stargazers_url": "https://api.github.com/repos/ehmorris/courses/stargazers",
     *         "contributors_url": "https://api.github.com/repos/ehmorris/courses/contributors",
     *         "subscribers_url": "https://api.github.com/repos/ehmorris/courses/subscribers",
     *         "subscription_url": "https://api.github.com/repos/ehmorris/courses/subscription",
     *         "commits_url": "https://api.github.com/repos/ehmorris/courses/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/ehmorris/courses/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/ehmorris/courses/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/ehmorris/courses/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/ehmorris/courses/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/ehmorris/courses/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/ehmorris/courses/merges",
     *         "archive_url": "https://api.github.com/repos/ehmorris/courses/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/ehmorris/courses/downloads",
     *         "issues_url": "https://api.github.com/repos/ehmorris/courses/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/ehmorris/courses/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/ehmorris/courses/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/ehmorris/courses/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/ehmorris/courses/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/ehmorris/courses/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/ehmorris/courses/deployments",
     *         "created_at": "2011-11-09T04:50:01Z",
     *         "updated_at": "2019-04-01T18:40:31Z",
     *         "pushed_at": "2013-04-21T05:40:23Z",
     *         "git_url": "git://github.com/ehmorris/courses.git",
     *         "ssh_url": "git@github.com:ehmorris/courses.git",
     *         "clone_url": "https://github.com/ehmorris/courses.git",
     *         "svn_url": "https://github.com/ehmorris/courses",
     *         "homepage": "",
     *         "size": 428,
     *         "stargazers_count": 0,
     *         "watchers_count": 0,
     *         "language": "JavaScript",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 18,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 18,
     *         "watchers": 0,
     *         "default_branch": "master"
     *     },
     *     {
     *         "id": 4854806,
     *         "node_id": "MDEwOlJlcG9zaXRvcnk0ODU0ODA2",
     *         "name": "Mechassault",
     *         "full_name": "ehmorris/Mechassault",
     *         "private": false,
     *         "owner": {
     *             "login": "ehmorris",
     *             "id": 654275,
     *             "node_id": "MDQ6VXNlcjY1NDI3NQ==",
     *             "avatar_url": "https://avatars0.githubusercontent.com/u/654275?v=4",
     *             "gravatar_id": "",
     *             "url": "https://api.github.com/users/ehmorris",
     *             "html_url": "https://github.com/ehmorris",
     *             "followers_url": "https://api.github.com/users/ehmorris/followers",
     *             "following_url": "https://api.github.com/users/ehmorris/following{/other_user}",
     *             "gists_url": "https://api.github.com/users/ehmorris/gists{/gist_id}",
     *             "starred_url": "https://api.github.com/users/ehmorris/starred{/owner}{/repo}",
     *             "subscriptions_url": "https://api.github.com/users/ehmorris/subscriptions",
     *             "organizations_url": "https://api.github.com/users/ehmorris/orgs",
     *             "repos_url": "https://api.github.com/users/ehmorris/repos",
     *             "events_url": "https://api.github.com/users/ehmorris/events{/privacy}",
     *             "received_events_url": "https://api.github.com/users/ehmorris/received_events",
     *             "type": "User",
     *             "site_admin": false
     *         },
     *         "html_url": "https://github.com/ehmorris/Mechassault",
     *         "description": "seek out and acquire all classes available at NEU",
     *         "fork": false,
     *         "url": "https://api.github.com/repos/ehmorris/Mechassault",
     *         "forks_url": "https://api.github.com/repos/ehmorris/Mechassault/forks",
     *         "keys_url": "https://api.github.com/repos/ehmorris/Mechassault/keys{/key_id}",
     *         "collaborators_url": "https://api.github.com/repos/ehmorris/Mechassault/collaborators{/collaborator}",
     *         "teams_url": "https://api.github.com/repos/ehmorris/Mechassault/teams",
     *         "hooks_url": "https://api.github.com/repos/ehmorris/Mechassault/hooks",
     *         "issue_events_url": "https://api.github.com/repos/ehmorris/Mechassault/issues/events{/number}",
     *         "events_url": "https://api.github.com/repos/ehmorris/Mechassault/events",
     *         "assignees_url": "https://api.github.com/repos/ehmorris/Mechassault/assignees{/user}",
     *         "branches_url": "https://api.github.com/repos/ehmorris/Mechassault/branches{/branch}",
     *         "tags_url": "https://api.github.com/repos/ehmorris/Mechassault/tags",
     *         "blobs_url": "https://api.github.com/repos/ehmorris/Mechassault/git/blobs{/sha}",
     *         "git_tags_url": "https://api.github.com/repos/ehmorris/Mechassault/git/tags{/sha}",
     *         "git_refs_url": "https://api.github.com/repos/ehmorris/Mechassault/git/refs{/sha}",
     *         "trees_url": "https://api.github.com/repos/ehmorris/Mechassault/git/trees{/sha}",
     *         "statuses_url": "https://api.github.com/repos/ehmorris/Mechassault/statuses/{sha}",
     *         "languages_url": "https://api.github.com/repos/ehmorris/Mechassault/languages",
     *         "stargazers_url": "https://api.github.com/repos/ehmorris/Mechassault/stargazers",
     *         "contributors_url": "https://api.github.com/repos/ehmorris/Mechassault/contributors",
     *         "subscribers_url": "https://api.github.com/repos/ehmorris/Mechassault/subscribers",
     *         "subscription_url": "https://api.github.com/repos/ehmorris/Mechassault/subscription",
     *         "commits_url": "https://api.github.com/repos/ehmorris/Mechassault/commits{/sha}",
     *         "git_commits_url": "https://api.github.com/repos/ehmorris/Mechassault/git/commits{/sha}",
     *         "comments_url": "https://api.github.com/repos/ehmorris/Mechassault/comments{/number}",
     *         "issue_comment_url": "https://api.github.com/repos/ehmorris/Mechassault/issues/comments{/number}",
     *         "contents_url": "https://api.github.com/repos/ehmorris/Mechassault/contents/{+path}",
     *         "compare_url": "https://api.github.com/repos/ehmorris/Mechassault/compare/{base}...{head}",
     *         "merges_url": "https://api.github.com/repos/ehmorris/Mechassault/merges",
     *         "archive_url": "https://api.github.com/repos/ehmorris/Mechassault/{archive_format}{/ref}",
     *         "downloads_url": "https://api.github.com/repos/ehmorris/Mechassault/downloads",
     *         "issues_url": "https://api.github.com/repos/ehmorris/Mechassault/issues{/number}",
     *         "pulls_url": "https://api.github.com/repos/ehmorris/Mechassault/pulls{/number}",
     *         "milestones_url": "https://api.github.com/repos/ehmorris/Mechassault/milestones{/number}",
     *         "notifications_url": "https://api.github.com/repos/ehmorris/Mechassault/notifications{?since,all,participating}",
     *         "labels_url": "https://api.github.com/repos/ehmorris/Mechassault/labels{/name}",
     *         "releases_url": "https://api.github.com/repos/ehmorris/Mechassault/releases{/id}",
     *         "deployments_url": "https://api.github.com/repos/ehmorris/Mechassault/deployments",
     *         "created_at": "2012-07-02T01:34:34Z",
     *         "updated_at": "2019-04-01T18:40:31Z",
     *         "pushed_at": "2013-03-23T22:31:38Z",
     *         "git_url": "git://github.com/ehmorris/Mechassault.git",
     *         "ssh_url": "git@github.com:ehmorris/Mechassault.git",
     *         "clone_url": "https://github.com/ehmorris/Mechassault.git",
     *         "svn_url": "https://github.com/ehmorris/Mechassault",
     *         "homepage": null,
     *         "size": 121,
     *         "stargazers_count": 1,
     *         "watchers_count": 1,
     *         "language": "Ruby",
     *         "has_issues": true,
     *         "has_projects": true,
     *         "has_downloads": true,
     *         "has_wiki": true,
     *         "has_pages": false,
     *         "forks_count": 0,
     *         "mirror_url": null,
     *         "archived": false,
     *         "disabled": false,
     *         "open_issues_count": 3,
     *         "license": null,
     *         "forks": 0,
     *         "open_issues": 3,
     *         "watchers": 1,
     *         "default_branch": "master"
     *     }
     *     ]
     */
}
